#!/bin/bash

# Update Packages
dnf update

# Add RPMFusion
rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Add codecs
rpm-ostree groupupdate core
rpm-ostree groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
rpm-ostree groupupdate sound-and-video

# Add Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Apps
# Zoom, Slack, Discord
flatpak install flathub us.zoom.Zoom com.slack.Slack com.discordapp.Discord

# Chrome
wget -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
rpm-ostree install ~/Downloads/google-chrome-stable_current_x86_64.rpm

echo Setup Complete. Please Reboot.
